name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync

    - name: Run linting
      run: uv run ruff check .

    - name: Run formatting check
      run: uv run ruff format --check .

    - name: Run tests
      run: uv run pytest tests/ -v

    - name: Test installation
      run: |
        uv pip install -e .
        uv run mcp-sync --help

    - name: Test basic functionality
      run: |
        uv run mcp-sync template
        uv run mcp-sync init

    - name: Verify config file exists
      run: |
        python -c "import os; print('.mcp.json exists' if os.path.exists('.mcp.json') else '.mcp.json missing')"
